// Stamps every build with an id, written to two places that must agree:
//   public/version.json   — fetched at runtime, never cached
//   src/lib/buildId.ts    — compiled INTO the bundle
// When they disagree, the running app is stale and says so. This exists
// because a cached index.html silently served an old app three separate
// times, and "did you even change it?" is the worst bug report to earn.
import { writeFileSync } from "node:fs";
import { execSync } from "node:child_process";

let sha = "local";
try { sha = execSync("git rev-parse --short HEAD").toString().trim(); } catch { /* not a repo */ }
const id = `${new Date().toISOString().slice(0, 16).replace(/\D/g, "")}-${sha}`;

writeFileSync("public/version.json", JSON.stringify({ id }) + "\n");
writeFileSync("src/lib/buildId.ts", `// generated by scripts/stamp.mjs — do not edit\nexport const BUILD_ID = ${JSON.stringify(id)};\n`);
console.log("build id:", id);
